### ISSUE TITLE
Ubuntu 16.04 issue with automake-1.15 (and solution)

### ISSUE THREAD

**Issue by SethM55** [nathanweeks/exonerate#11]
Hi,

Automake 1.15 has known issues that didn't appear with older versions, but is the only version that comes through apt on Ubuntu 16.04.  Exonerate generates an "unable to find aclocal" error on automake 1.15, but to work around this after cloning the git you need to manually run:
sudo aclocal
sudo automake
sudo make
You MAY need to run ./configure before that (I did, but didn't test without a preconfigured run.  I also needed to run automake with an '--add-missing' tag, but I've been trying multiple work arounds and this may not be necessary, automake prompted me to add it though.

I just wanted to get a notice of this somewhere in case someone else runs into the problem

**Comment by nathanweeks** [comment]
Thanks for the heads up, Seth. That must have been the v2.4.0 release, which does have creaky-old versions of the autotools-generated files. Regenerating those files using `autoreconf -i` as described the instructions for building the developer version (which doesn't come with the autotools-generated files) should also work. Other users with a modern build environment will likely run into the same issue, so I suppose the build instructions could be amended to recommend that users always regenerate those files when building the v2.4.0 release.
