### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by gultag** [nathanweeks/exonerate#12]
Hi,
I got this error during the compilation:

$ ./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking whether make sets $(MAKE)... yes
checking for working aclocal-1.4... missing
checking for working autoconf... missing
checking for working automake-1.4... missing
checking for working autoheader... missing
checking for working makeinfo... found
checking for gcc... gcc
checking for C compiler default output file name... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables... 
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for a BSD-compatible install... /usr/bin/install -c
checking whether make sets $(MAKE)... (cached) yes
checking for an ANSI C-conforming const... yes
checking for inline... inline
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking limits.h usability... yes
checking limits.h presence... yes
checking for limits.h... yes
checking errno.h usability... yes
checking errno.h presence... yes
checking for errno.h... yes
checking math.h usability... yes
checking math.h presence... yes
checking for math.h... yes
checking for strings.h... (cached) yes
checking ctype.h usability... yes
checking ctype.h presence... yes
checking for ctype.h... yes
checking for sys/stat.h... (cached) yes
checking for sys/types.h... (cached) yes
checking time.h usability... yes
checking time.h presence... yes
checking for time.h... yes
checking for unistd.h... (cached) yes
checking build system type... i386-apple-darwin17.2.0
checking host system type... i386-apple-darwin17.2.0
Set host to i386-apple-darwin17.2.0
i386-apple-darwin17.2.0
Customising build for OSX
Set source_root_dir to /Users/spribill/Downloads/exonerate-2.2.0/exonerate
----------------------------------------------------------------
checking for socklen_t... yes
checking for pkg-config... no
ERROR: Could not find pkg-config ... is glib-2 installed ???

The thing is that I have installed glib2-dev, according to the instruction in readme. I also installed glib2-shlibs, glibmm2.4-dev, and glibmm2.4-shlibs, since I've read that it might help, but it didn't. 
For that I used the latest version of fink, if that matters.
Is there anything that could help?

Thank you,
Gulnara

**Comment by nathanweeks** [comment]
It looks like the fink "pkgconfig" package provides the pkg-config executable:

http://pdb.finkproject.org/pdb/package.php/pkgconfig

**Comment by gultag** [comment]
It helped. Thank you!

**Comment by nathanweeks** [comment]
Good to know. I'll go ahead and close this issue; feel free to reopen it if you encounter another issue compiling exonerate on MacOS.
