### ISSUE TITLE
running est2genome in chunks

### ISSUE THREAD

**Issue by norazrin** [nathanweeks/exonerate#13]
Hi, 
i been trying to run exonerate for est2genome module and here is the basic code (sorry im a newbie so dont know much about command line):
#!/bin/bash

#$ -S /bin/bash
#$ -cwd                 #Job runs in current directory -where submitted from
#$ -V                   #Job inherits current environment
#$ -pe smp.pe 8

#exonerate first trial for chunking the query database

 exonerate /mnt/fls01-home01/mqbpkna2/scratch/January_2018/exonerate-2.2.0-x86_64/bin/exonerate-2.2.0-x86_64 --model est2genome /mnt/fls01-home01/mqbpkna2/scratch/January_2018/exo
nerate-2.2.0-x86_64/bin/transcripts.fasta /mnt/fls01-home01/mqbpkna2/scratch/January_2018/exonerate-2.2.0-x86_64/bin/Acomosus_321_v3.fa --querychunkid 1 --querychunktotal 8
 exonerate /mnt/fls01-home01/mqbpkna2/scratch/January_2018/exonerate-2.2.0-x86_64/bin/exonerate-2.2.0-x86_64 --model est2genome /mnt/fls01-home01/mqbpkna2/scratch/January_2018/exo
nerate-2.2.0-x86_64/bin/transcripts.fasta /mnt/fls01-home01/mqbpkna2/scratch/January_2018/exonerate-2.2.0-x86_64/bin/Acomosus_321_v3.fa --querychunkid 2 --querychunktotal 8
 exonerate /mnt/fls01-home01/mqbpkna2/scratch/January_2018/exonerate-2.2.0-x86_64/bin/exonerate-2.2.0-x86_64 --model est2genome /mnt/fls01-home01/mqbpkna2/scratch/January_2018/exo
nerate-2.2.0-x86_64/bin/transcripts.fasta /mnt/fls01-home01/mqbpkna2/scratch/January_2018/exonerate-2.2.0-x86_64/bin/Acomosus_321_v3.fa --querychunkid 3 --querychunktotal 8
 exonerate /mnt/fls01-home01/mqbpkna2/scratch/January_2018/exonerate-2.2.0-x86_64/bin/exonerate-2.2.0-x86_64 --model est2genome /mnt/fls01-home01/mqbpkna2/scratch/January_2018/exo
nerate-2.2.0-x86_64/bin/transcripts.fasta /mnt/fls01-home01/mqbpkna2/scratch/January_2018/exonerate-2.2.0-x86_64/bin/Acomosus_321_v3.fa --querychunkid 4 --querychunktotal 8
 exoberate /mnt/fls01-home01/mqbpkna2/scratch/January_2018/exonerate-2.2.0-x86_64/bin/exonerate-2.2.0-x86_64 --model est2genome /mnt/fls01-home01/mqbpkna2/scratch/January_2018/exo
nerate-2.2.0-x86_64/bin/transcripts.fasta /mnt/fls01-home01/mqbpkna2/scratch/January_2018/exonerate-2.2.0-x86_64/bin/Acomosus_321_v3.fa --querychunkid 5 --querychunktotal 8
 exonerate /mnt/fls01-home01/mqbpkna2/scratch/January_2018/exonerate-2.2.0-x86_64/bin/exonerate-2.2.0-x86_64 --model est2genome /mnt/fls01-home01/mqbpkna2/scratch/January_2018/exo
nerate-2.2.0-x86_64/bin/transcripts.fasta /mnt/fls01-home01/mqbpkna2/scratch/January_2018/exonerate-2.2.0-x86_64/bin/Acomosus_321_v3.fa --querychunkid 6 --querychunktotal 8
 exonerate /mnt/fls01-home01/mqbpkna2/scratch/January_2018/exonerate-2.2.0-x86_64/bin/exonerate-2.2.0-x86_64 --model est2genome /mnt/fls01-home01/mqbpkna2/scratch/January_2018/exo
nerate-2.2.0-x86_64/bin/transcripts.fasta /mnt/fls01-home01/mqbpkna2/scratch/January_2018/exonerate-2.2.0-x86_64/bin/Acomosus_321_v3.fa --querychunkid 7 --querychunktotal 8
 exonerate /mnt/fls01-home01/mqbpkna2/scratch/January_2018/exonerate-2.2.0-x86_64/bin/exonerate-2.2.0-x86_64 --model est2genome /mnt/fls01-home01/mqbpkna2/scratch/January_2018/exo
nerate-2.2.0-x86_64/bin/transcripts.fasta /mnt/fls01-home01/mqbpkna2/scratch/January_2018/exonerate-2.2.0-x86_64/bin/Acomosus_321_v3.fa --querychunkid 8 --querychunktotal 8

exit 0 

BUT. there is error: exo_1st_pineapple.sh: line 11: exonerate: command not found

please help me to solve this. thanks!

**Comment by nathanweeks** [comment]
Hi @norazrin , it's somewhat difficult to visually parse the job script due to line wrapping, but I suspect that the `exonerate` program isn't in your PATH, and the absolute pathname to your exonerate executable is:
```
/mnt/fls01-home01/mqbpkna2/scratch/January_2018/exonerate-2.2.0-x86_64/bin/exonerate-2.2.0-x86_64
```

If so, try removing the `exonerate` command from the beginning of each line, so instead of:
```
exonerate /mnt/fls01-home01/mqbpkna2/scratch/January_2018/exonerate-2.2.0-x86_64/bin/exonerate-2.2.0-x86_64 ...
```
you would just have:
```
/mnt/fls01-home01/mqbpkna2/scratch/January_2018/exonerate-2.2.0-x86_64/bin/exonerate-2.2.0-x86_64 ...
```
If that doesn't work, please post your job script inside a code block in Git markdown to prevent line wrapping.

**Comment by norazrin** [comment]
it seems to work now (im using computer farm btw), thanks for your suggestion!
i guess i have to wait for the outcome? sooo freaking nervous but at least im happy it runs!
lol

**Comment by nathanweeks** [comment]
Good to know! I'll mark the issue as closed. Feel free to reopen it or open a new issue if you have additional problems.
