### ISSUE TITLE
exonerate#make error

### ISSUE THREAD

**Issue by ashaneev** [nathanweeks/exonerate#17]
dcb@dcb-OptiPlex-3020:~/Documents/sof/exonerate-master$ sudo make
Making all in doc
make[1]: Entering directory `/home/dcb/Documents/sof/exonerate-master/doc'
Making all in man
make[2]: Entering directory `/home/dcb/Documents/sof/exonerate-master/doc/man'
Making all in man1
make[3]: Entering directory `/home/dcb/Documents/sof/exonerate-master/doc/man/man1'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/home/dcb/Documents/sof/exonerate-master/doc/man/man1'
make[3]: Entering directory `/home/dcb/Documents/sof/exonerate-master/doc/man'
make[3]: Nothing to be done for `all-am'.
make[3]: Leaving directory `/home/dcb/Documents/sof/exonerate-master/doc/man'
make[2]: Leaving directory `/home/dcb/Documents/sof/exonerate-master/doc/man'
make[2]: Entering directory `/home/dcb/Documents/sof/exonerate-master/doc'
make[2]: Nothing to be done for `all-am'.
make[2]: Leaving directory `/home/dcb/Documents/sof/exonerate-master/doc'
make[1]: Leaving directory `/home/dcb/Documents/sof/exonerate-master/doc'
Making all in src
make[1]: Entering directory `/home/dcb/Documents/sof/exonerate-master/src'
Making all in struct
make[2]: Entering directory `/home/dcb/Documents/sof/exonerate-master/src/struct'
gcc -DPACKAGE_NAME=\"exonerate\" -DPACKAGE_TARNAME=\"exonerate\" -DPACKAGE_VERSION=\"2.4.0\" -DPACKAGE_STRING=\"exonerate\ 2.4.0\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"exonerate\" -DVERSION=\"2.4.0\" -D_XOPEN_SOURCE=600 -DHAVE_DECL__XOPEN_PATH_MAX=0 -D_XOPEN_PATH_MAX=1024 -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_LIMITS_H=1 -DHAVE_ERRNO_H=1 -DHAVE_MATH_H=1 -DHAVE_STRINGS_H=1 -DHAVE_CTYPE_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_TIME_H=1 -DHAVE_UNISTD_H=1 -I.  -DCUSTOM_GUINT64_FORMAT="\"lu\""   -g -O2  -DG_DISABLE_ASSERT -O3 -finline-functions -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -MT fsm.test.o -MD -MP -MF .deps/fsm.test.Tpo -c -o fsm.test.o fsm.test.c
In file included from fsm.test.c:17:0:
fsm.h:24:37: fatal error: glib.h: No such file or directory
 #include <glib.h> /* For CHAR_BIT */
                                     ^
compilation terminated.
make[2]: *** [fsm.test.o] Error 1
make[2]: Leaving directory `/home/dcb/Documents/sof/exonerate-master/src/struct'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/dcb/Documents/sof/exonerate-master/src'
make: *** [all-recursive] Error 1

**Comment by nathanweeks** [comment]
Hi @ashaneev ,

glib development headers must be installed (see https://github.com/nathanweeks/exonerate/issues/15#issuecomment-376565588)
