### ISSUE TITLE
how to get protein file output

### ISSUE THREAD

**Issue by U201412486** [nathanweeks/exonerate#19]
Hi,
  How can I get my protein sequence after I run `exonerate --model est2genome`and get gff3 file?
  Thanks,
  sun,

**Comment by hyphaltip** [comment]
Did you look at the —ryo documented options in thE man page.

Jason Stajich, PhD
jasonstajich.phd@gmail.com

**Comment by djinnome** [comment]
Hi Sun,

Jason is right, the –ryo option allows you to roll your own gff output, but there is also a –showtargetgff option that I think will do what you want.

Sincerely,

Jeremy

**Comment by U201412486** [comment]
Thanks,It is my oversight.

**Comment by nathanweeks** [comment]
@hyphaltip & @djinnome: thanks for chiming in!

@U201412486 : I'll mark this issue as closed. Feel free to reopen if you still need assistance with this.
