### ISSUE TITLE
GLib-ERROR **: failed to allocate bytes

### ISSUE THREAD

**Issue by sjfleck** [nathanweeks/exonerate#21]
I have gene models for a MaSuRCA assembly, but it's not a great assembly. I used the online tool CoGe to create a "pseudo assembly, where it maps the MaSuRCA contigs onto a higher quality reference for a more contiguous assembly. I want to transfer the gene models that were created for a MaSuRCA assembly to the "pseudo assembly" created by CoGe. The ultimate goal to to have a new .gff file.

I was able to install exonerate without errors on my university's Cluster. I first ran it on our debug partition that doesn't use much memory and it failed because it exceeded the memory I set (48 GB). Here is the command:

_pseudo_assembly="/path/to/pseudo/assembly/pseudoassembly.faa"
gene_model="/path/to/gene/models/SFGP_GEN1Assembly.all.faa"
exonerate --model protein2genome -c 16 --showquerygff yes -q $gene_model -t $pseudo_assembly_ 

Then I tried to run it on a larger partition that can handle up to 750 GB of Memory, but it experienced a segmentation fault. Here is the command:

_exonerate --model protein2genome -c 32 --showquerygff yes -q $gene_model -t $pseudo_assembly_ 

I saw that the only two parameters that dealt with memory were "--dpmemory" and "--fsmmemory", so I decided to max them out to the full memory I was allocating. The program ran, but failed after 30 minutes. Here is the command:

_exonerate --model protein2genome -c 16 --showquerygff yes -M 500000 -D 500000 -q $gene_model -t $pseudo_assembly_ 

The error was: 
_(process:52261): GLib-ERROR **: 11:17:13.991: gmem.c:105: failed to allocate 18446744072033491433 bytes_

That is more bytes than I'll ever have access to. I tried lowering the -M and -D flags, but ended up with the same kind of error. Do you have any recommendations for fixing this error. Thanks!

**Comment by sjfleck** [comment]
Can I email you the files privately? They're too big for a GitHub comment.

**Comment by nathanweeks** [comment]
If they're too big for GitHub, they're probably too big to receive via email. Are you able to post a link to a shared folder (Google Drive, OneDrive, Box, etc.?). If beneficial, I could create a shared folder on one of those platforms.

**Comment by sjfleck** [comment]
Here is a link. You should have access to the 2 files I have in there
https://drive.google.com/drive/folders/1iCoDlHsriUZt1YTSKqBtC4Iufouw9ARQ?usp=sharing

**Comment by nathanweeks** [comment]
Got 'em, will have a look.

**Comment by nathanweeks** [comment]
@sjfleck : I've tried running exonerate built from the master branch of this repo, and it seems to work, at least, using a single core (`exonerate --model protein2genome --showquerygff yes -q $gene_model -t $pseudo_assembly`), and letting it run for over an hour (looks like it would take ~2 days on the somewhat-old/slow-ish server). The memory usage (resident set size) hovered between ~2.1 - 2.4 GB.

Could you try first using a single core (as exonerate's multi-threading is somewhat buggy), and if that doesn't work, try building from the master branch (which has multi-threading disabled)?

If single-threaded performance is unacceptable, you could try parallelizing by partitioning the input sequence, running multiple concurrent copies of (single-threaded) exonerate, and aggregating the output streams using a tool like GNU parallel.

**Comment by Yorks0n** [comment]
> @sjfleck : I've tried running exonerate built from the master branch of this repo, and it seems to work, at least, using a single core (`exonerate --model protein2genome --showquerygff yes -q $gene_model -t $pseudo_assembly`), and letting it run for over an hour (looks like it would take ~2 days on the somewhat-old/slow-ish server). The memory usage (resident set size) hovered between ~2.1 - 2.4 GB.
> 
> Could you try first using a single core (as exonerate's multi-threading is somewhat buggy), and if that doesn't work, try building from the master branch (which has multi-threading disabled)?
> 
> If single-threaded performance is unacceptable, you could try parallelizing by partitioning the input sequence, running multiple concurrent copies of (single-threaded) exonerate, and aggregating the output streams using a tool like GNU parallel.

I encountered the same problem while using exonerate installed by conda. It seems that this version will run with two cores defaultly (without set -c 2). I changed to use exonerate built from the master branch and it worked properly.

**Comment by sjfleck** [comment]
Nathan and YorksOn thanks for your suggestions! I ultimately used GeMoMa to accomplish what I was trying to do. In the future, I'll also build exonerate from the master branch and try that out too
