### ISSUE TITLE
protein2genome:bestfit goes immediately to sleep on WSL command line call

### ISSUE THREAD

**Issue by iPsychonaut** [nathanweeks/exonerate#27]
Anytime I call the protein2genome:bestfit command I the program stalls out waiting for some unknown resources to being, but never gets them, even after hours. Here is an example command
exonerate --model protein2genome:bestfit \
--maxintron 100 \
--percent 25 \
--showalignment true \
--showtargetgff true \
--showvulgar false \
--query "./gene_cluster.fasta" \
--target "./contig_2716_pilon_consensus.fasta"

**Comment by iPsychonaut** [comment]
exonerate --model protein2genome \
--maxintron 100 \
--percent 25 \
--showalignment true \
--showtargetgff true \
--showvulgar false \
--query "./gene_cluster.fasta" \
--target "./contig_2716_pilon_consensus.fasta" \
-M 6 \

This command, replaceing protein2genome  with the protein2genome:bestfit /, removing -E / -S no / from the command and adding multi-threading as well with the -M 6 allow the command to run in a matter of milliseconds.

**Comment by nathanweeks** [comment]
> exonerate --model protein2genome --maxintron 100 --percent 25 --showalignment true --showtargetgff true --showvulgar false --query "./gene_cluster.fasta" --target "./contig_2716_pilon_consensus.fasta" -M 6 \
> 
> This command, replaceing protein2genome with the protein2genome:bestfit /, removing -E / -S no / from the command and adding multi-threading as well with the -M 6 allow the command to run in a matter of milliseconds.

I wasn't clear on the command that hung, but if it included -E / --exhaustive, note that exonerate 2.4 had a bug where sometimes an exhaustive search would hang (https://github.com/nathanweeks/exonerate/issues/16). That issue appeared to be resolved in the master branch. Could you try building exonerate from the master branch? If that's still impacted by the issue, could you re-copy/paste both the command that hung and the command that worked?

**Comment by iPsychonaut** [comment]
exonerate --model protein2genome:bestfit
--maxintron 100
--percent 5
--showalignment yes
--showtargetgff true
--showvulgar no
-S no
-E
-V 5
-M 6
--query ./gene_cluster.fasta
--target ./A1_3_contig_29_pilon_consensus.fasta
> ./A1_3_contig_29_pilon_consensus.gtf

Did not hang-up, thank you for your direction and upkeep 🙏
