### ISSUE TITLE
STDERR:  WARNING **: Score [168] greater than previous [137]

### ISSUE THREAD

**Issue by BioWu** [nathanweeks/exonerate#7]
Hello, nathanweeks,
    I recently had used EXONERATE in protein2genome alignments, but several species of error informations showed in this process as this title said. I checked your source code(opair.c), but I failed to understand why this lower score results this error-info. Also, if this meant results of those alignment are not optimal?

Best

Vincent

**Comment by nathanweeks** [comment]
It looks like OPair_next_path() expects Optimal_find_path() to return alignments with monotonically-decreasing scores. 

Did you use the final original exonerate v2.4.0 release, or the development version (which has bug fixes)? If you used v2.4.0, could you please try with the development version (see README.md)? If they both result in the same error, could you please provide data that reproduces the problem so I can come up with a fix? 

I'll add that this issue should be encountered only when --exhaustive is specified, so excluding --exhaustive should work around the problem. In the development branch, I fixed a bug when --refine is specified (https://github.com/nathanweeks/exonerate/commit/cc40cca66f5aa441bb843923d5fe1ea2f99064ec) that bears some similarity to this one, so I'm wondering if there may be a related solution.
