### ISSUE TITLE
The make does not appear to be working on my linux machine

### ISSUE THREAD

**Issue by bmusungu** [nathanweeks/exonerate#9]
Been trying to compile the exonerate file but keep getting the bottom errors

DEPDIR=.deps depmode=none /bin/sh ../../depcomp \
gcc -DPACKAGE_NAME=\"exonerate\" -DPACKAGE_TARNAME=\"exonerate\" -DPACKAGE_VERSION=\"2.4.0\" -DPACKAGE_STRING=\"exonerate\ 2.4.0\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"exonerate\" -DVERSION=\"2.4.0\" -D_XOPEN_SOURCE=600 -DHAVE_DECL__XOPEN_PATH_MAX=0 -D_XOPEN_PATH_MAX=1024 -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_LIMITS_H=1 -DHAVE_ERRNO_H=1 -DHAVE_MATH_H=1 -DHAVE_STRINGS_H=1 -DHAVE_CTYPE_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_TIME_H=1 -DHAVE_UNISTD_H=1 -I.  -DCUSTOM_GUINT64_FORMAT="\"lu\""   -g -O2 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include  -DG_DISABLE_ASSERT -O3 -finline-functions -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -c fsm.test.c
/bin/sh: ../../depcomp: No such file or directory
Makefile:396: recipe for target 'fsm.test.o' failed
make[2]: **\* [fsm.test.o] Error 127
make[2]: Leaving directory '/home/bryan/exonerate/src/struct'
Makefile:258: recipe for target 'all-recursive' failed
make[1]: **\* [all-recursive] Error 1
make[1]: Leaving directory '/home/bryan/exonerate/src'
Makefile:284: recipe for target 'all-recursive' failed
make: **\* [all-recursive] Error 1

Thanks 

Bryan

**Comment by nathanweeks** [comment]
I apologize for the slow response. It looks like you checked out the _develop_ branch. Did you get an error message when running ```autoreconf -i```?

**Comment by wuxiaopei0509** [comment]
I have the same problem.how did you solve the issue at last?
Thanks

**Comment by Ofsm** [comment]
sometime with this issue? Im have the same problem

**Comment by nathanweeks** [comment]
I've added a [Dockerfile](https://github.com/nathanweeks/exonerate/blob/master/Dockerfile) to the repo that, in addition to providing a mechanism for easily building a Docker image with exonerate, also illustrates how to install (into /usr/local/) on Ubuntu 20.04. Hopefully that provides enough hints to build exonerate in the target environment, but if not, please provide details on the software environment (target operating system version, compiler, etc.), the version of exonerate (e.g., git commit) that is being compiled, the list of commands used to configure/make.
